### ISSUE TITLE
Separate card data to a file of its own

### ISSUE THREAD

**Issue by xird** [xird/rok#1]
The card definitions are currently in ROKServerGame.js. This clutters up the symbol browsers in IDEs, and makes scrolling up and down the file tedious.

More importantly, in order to pass card data to the front end, we need to be able to include the card data on the client side. Moving the card definitions to a separate file makes this easy.

The card data is required on the front end if we want to allow clients to render the cards themselves based on the card attributes, instead of just showing an image.

**Comment by S-Bartfast** [comment]
Card details are now stored in ROKCards.js
